server:
  port: 8090

spring:
  application:
    name: apigateway
  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: PRODUCT
          uri: lb://PRODUCT
          predicates:
            - Path=/api/v1/product/**
          filters:
            - StripPrefix=2

        - id: USER
          uri: lb://USER
          predicates:
            - Path=/api/v1/user/**
          filters:
            - StripPrefix=2

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/