server:
  port: 8090

spring:
  application:
    name: apigateway
  cloud:
    config:
      enabled: false
    gateway:
      server:
        webflux:                    # ✅ new key prefix
          routes:
            - id: PRODUCT
              uri: lb://PRODUCT
              predicates:
                - Path=/api/v1/product/**
              filters:
                - StripPrefix=2
                - name: AuthenticationGatewayFilter
                  args:
                     Enabled: true
                     roles: User
                - name: LoggingOrdersFilter

            - id: USER
              uri: lb://USER
              predicates:
                - Path=/api/v1/user/**
              filters:
                - StripPrefix=2
                - name: AuthenticationGatewayFilter
                  args:
                    Enabled: true
                    roles : User

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
#  endpoint:
#    gateway:
#      enabled: true