spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: sharathdotnet7@gmail.com
    password:          # NOT your Gmail login password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: localhost:9092

    admin:
      auto-create: true

    consumer:
      group-id: kafka-notification
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.trust.microservices.*"

    listener:
      ack-mode: record

server:
  port: 8083