spring:
  kafka:
    bootstrap-servers: localhost:9092

    admin:
      auto-create: true

    consumer:
      group-id: kafka-notification
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.trust.microservices.*"

    listener:
      ack-mode: record

server:
  port: 8083